namespace TNetSdk
{
	public enum RequestType
	{
		HeartBeat = 0,
		Login = 1,
		Logout = 2,
		GetRoomList = 3,
		JoinRoom = 4,
		AutoJoin = 5,
		CreateRoom = 6,
		GenericMessage = 7,
		ChangeRoomName = 8,
		ChangeRoomPassword = 9,
		ObjectMessage = 10,
		BroadcastMessage = 11,
		SetRoomVariables = 12,
		SetUserVariables = 13,
		SetUserStatus = 14,
		CallExtension = 15,
		LeaveRoom = 16,
		StartRoom = 17,
		DestroyRoom = 18,
		LockSth = 19,
		UnLockSth = 20,
		SubscribeRoomGroup = 21,
		UnsubscribeRoomGroup = 22,
		SpectatorToPlayer = 23,
		PlayerToSpectator = 24,
		ChangeRoomCapacity = 25,
		PublicMessage = 26,
		PrivateMessage = 27,
		ModeratorMessage = 28,
		AdminMessage = 29,
		KickUser = 30,
		BanUser = 31,
		ManualDisconnection = 32,
		FindRooms = 33,
		FindUsers = 34,
		PingPong = 35,
		InitBuddyList = 200,
		AddBuddy = 201,
		BlockBuddy = 202,
		RemoveBuddy = 203,
		SetBuddyVariables = 204,
		GoOnline = 205,
		InviteUser = 300,
		InvitationReply = 301,
		CreateSFSGame = 302,
		QuickJoinGame = 303
	}
}
