namespace TNetSdk
{
	public enum TNetEventRoom
	{
		GET_ROOM_LIST = 2,
		ROOM_REMOVE = 7,
		ROOM_CREATION = 4,
		ROOM_JOIN = 9,
		USER_ENTER_ROOM = 10,
		USER_EXIT_ROOM = 12,
		USER_BE_KICKED = 14,
		OBJECT_MESSAGE = 25,
		ROOM_VARIABLES_UPDATE = 18,
		USER_VARIABLES_UPDATE = 20,
		USER_STATE = 22,
		ROOM_NAME_CHANGE = 16,
		LOCK_STH = 27,
		UNLOCK_STH = 29,
		ROOM_START = 31,
		ROOM_MASTER_CHANGE = 32,
		ROOM_REMOVE_RES = 6
	}
}
